### ISSUE TITLE
Storage for funding agency logos

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/TrixiParticles.jl#438]
Similar to https://github.com/trixi-framework/Trixi.jl/issues/1390.

**Comment by efaulhaber** [comment]
```
https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/ae2a91d1-7c10-4e0f-8b92-6ed1c43ddc28
```
![278250497-a9791026-75a6-48fd-9fef-633e58b80725](https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/ae2a91d1-7c10-4e0f-8b92-6ed1c43ddc28)

**Comment by svchb** [comment]
`https://github.com/user-attachments/assets/d863c64c-b7d0-40c4-aede-874c0b22ee4c`
<img width="850" height="567" alt="Image" src="https://github.com/user-attachments/assets/d863c64c-b7d0-40c4-aede-874c0b22ee4c" />

**Comment by svchb** [comment]
`https://github.com/user-attachments/assets/d9861c0f-3e19-485e-9e57-e27c44d2d3b8`
<img width="421" height="343" alt="Image" src="https://github.com/user-attachments/assets/d9861c0f-3e19-485e-9e57-e27c44d2d3b8" />

**Comment by svchb** [comment]
`https://github.com/user-attachments/assets/f562f643-4179-4569-9ffb-b10871be6ee4`
<img width="712" height="149" alt="Image" src="https://github.com/user-attachments/assets/f562f643-4179-4569-9ffb-b10871be6ee4" />
