### ISSUE TITLE
Storage for docs images

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/TrixiParticles.jl#448]
Like #438, but for docs images.

> Since I am not a fan of storing binary blobs in our repo, I create this issue to collect such logos. Feel free to add new ones at the bottom as a reply to this (permanently closed) issue, but with only a single logo per post please. If an existing logo is deprecated and to be replaced by another one, please mark it **boldly** in the original post that a new logo has been added and link to the new post, but _keep the old one_ such that existing links continue to work.

Posted by @sloede in https://github.com/trixi-framework/Trixi.jl/issues/1390.

**Comment by efaulhaber** [comment]
Plotted with 200 dpi. That seems high enough to be perfectly sharp in the docs, but still has a reasonably small file size.
```
https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/95821154-577d-4323-ba57-16ef02ea24e0
```
![default_example_plot](https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/95821154-577d-4323-ba57-16ef02ea24e0)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/8466dbed-b1b1-4fce-ab2d-8b93b5cda833`
![osc_beam 0247](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/8466dbed-b1b1-4fce-ab2d-8b93b5cda833)

**Comment by svchb** [comment]
'https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/e05ace63-e330-441a-a391-eda3d2764074`
![osc_beam 0247](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/e05ace63-e330-441a-a391-eda3d2764074)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/d7c6eedd-7173-4879-b62e-3e6d4bc5091f`
![296170691-bb5283d8-07fe-4fe7-b7f1-2c00fd166ee8](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/d7c6eedd-7173-4879-b62e-3e6d4bc5091f)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/4c4c537a-8585-4456-9a1b-8b5adbf68533`
![output_movie-ezgif com-video-to-gif-converter](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/4c4c537a-8585-4456-9a1b-8b5adbf68533)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/76a2b235-1b49-465f-a207-76859410b783`
![dam_break_3d 0091](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/76a2b235-1b49-465f-a207-76859410b783)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/06a522f0-424f-49d3-afd0-29593373aa29`
![falling_water_column 0099](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/06a522f0-424f-49d3-afd0-29593373aa29)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/8e7991f6-fd2f-429b-8eb8-61be983cbe2a`
![test](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/8e7991f6-fd2f-429b-8eb8-61be983cbe2a)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/1dfa9dcf-7fc1-4221-ad83-a54c5d9ab9fb`
![osc_drop-ezgif com-video-to-gif-converter](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/1dfa9dcf-7fc1-4221-ad83-a54c5d9ab9fb)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/f9a542bf-956b-4647-843b-94cbb085a4fa`
![periodic_channel](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/f9a542bf-956b-4647-843b-94cbb085a4fa)

**Comment by svchb** [comment]
Larger particle version
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/e757d0a2-d1bc-486a-8ec9-7e2dc0bbe700`
![dam_break_2d 0071](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/e757d0a2-d1bc-486a-8ec9-7e2dc0bbe700)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/7cabf4d1-736a-466b-b376-0fca93c1653a`
![dam_break_plate 0012](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/7cabf4d1-736a-466b-b376-0fca93c1653a)

**Comment by svchb** [comment]
sphere version
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/888b2898-f99a-4a4e-97ea-338a39b87747`
![dam_break_2d_sph_part 0071](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/888b2898-f99a-4a4e-97ea-338a39b87747)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/217c80b5-3472-41c9-8003-7163641dd452`
![test](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/217c80b5-3472-41c9-8003-7163641dd452)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/b3964f68-2782-43e6-b6ff-be96f9f224ae`
![test](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/b3964f68-2782-43e6-b6ff-be96f9f224ae)

**Comment by efaulhaber** [comment]
```
https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/01289e3b-98ce-4b2d-8151-cd20782d5823
```

![density_diffusion_2d](https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/01289e3b-98ce-4b2d-8151-cd20782d5823)

**Comment by efaulhaber** [comment]
```
https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/440debc9-6051-4a3b-aa9c-02a6b32fccf3
```

![density_diffusion_tank](https://github.com/trixi-framework/TrixiParticles.jl/assets/44124897/440debc9-6051-4a3b-aa9c-02a6b32fccf3)

**Comment by svchb** [comment]
`https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/fac6c41f-7af8-4936-9dd5-b6ff2b9f6ff4`
![hydro_p](https://github.com/trixi-framework/TrixiParticles.jl/assets/10238714/fac6c41f-7af8-4936-9dd5-b6ff2b9f6ff4)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/89f0b7e3-5d47-4eba-9d29-34cf54f1b246
```
![image](https://github.com/user-attachments/assets/89f0b7e3-5d47-4eba-9d29-34cf54f1b246)

```
https://github.com/user-attachments/assets/8e1c2a6d-3b28-4f75-991f-0d0ecc9f6db1
```
![image-2](https://github.com/user-attachments/assets/8e1c2a6d-3b28-4f75-991f-0d0ecc9f6db1)

```
https://github.com/user-attachments/assets/66c423ae-28ce-4d48-aa52-777726a3a677
```
![image-3](https://github.com/user-attachments/assets/66c423ae-28ce-4d48-aa52-777726a3a677)

```
https://github.com/user-attachments/assets/920bb4f1-1336-4e77-b06d-d5b46ca0d8d5
```
![image-4](https://github.com/user-attachments/assets/920bb4f1-1336-4e77-b06d-d5b46ca0d8d5)

```
https://github.com/user-attachments/assets/1ea2002e-e9b3-4fca-8ba6-2b2413402183
```
![image-5](https://github.com/user-attachments/assets/1ea2002e-e9b3-4fca-8ba6-2b2413402183)

```
https://github.com/user-attachments/assets/a9332817-2b09-4d8a-8800-25fd8941ced2
```
![image-6](https://github.com/user-attachments/assets/a9332817-2b09-4d8a-8800-25fd8941ced2)

```
https://github.com/user-attachments/assets/06fa1915-65a4-4474-b096-81db9a05eea9
```
![image-7](https://github.com/user-attachments/assets/06fa1915-65a4-4474-b096-81db9a05eea9)

```
https://github.com/user-attachments/assets/85171c6d-5e23-4274-b066-419d9718209a
```
![image-8](https://github.com/user-attachments/assets/85171c6d-5e23-4274-b066-419d9718209a)


```
https://github.com/user-attachments/assets/b7f20461-128f-4694-b306-091060f16a07
```
![image-9](https://github.com/user-attachments/assets/b7f20461-128f-4694-b306-091060f16a07)

**Comment by svchb** [comment]
`https://github.com/user-attachments/assets/108a55c5-888c-457c-8308-eb4a533d0833`
![291280080-45c90fd2-984b-4eee-b130-e691cefb33ab](https://github.com/user-attachments/assets/108a55c5-888c-457c-8308-eb4a533d0833)

**Comment by svchb** [comment]
`https://github.com/user-attachments/assets/28599b08-f30a-49fa-b389-720442855fd5`
![291288735-7565a13f-9532-4a69-9f81-e79505400b1c](https://github.com/user-attachments/assets/28599b08-f30a-49fa-b389-720442855fd5)

**Comment by efaulhaber** [comment]
```
https://github.com/user-attachments/assets/d52c5e21-45c0-419e-9038-ca8002128da0
```
<img width="1624" alt="Screenshot 2024-11-12 at 10 56 03" src="https://github.com/user-attachments/assets/d52c5e21-45c0-419e-9038-ca8002128da0">

```
https://github.com/user-attachments/assets/6e975d2c-82ed-4d53-936b-bb0beafaf515
```
<img width="1624" alt="Screenshot 2024-11-12 at 10 57 28" src="https://github.com/user-attachments/assets/6e975d2c-82ed-4d53-936b-bb0beafaf515">

```
https://github.com/user-attachments/assets/10dcf7eb-5808-4d4d-9db8-4beb25b5e51a
```
<img width="1624" alt="Screenshot 2024-11-12 at 10 57 53" src="https://github.com/user-attachments/assets/10dcf7eb-5808-4d4d-9db8-4beb25b5e51a">

**Comment by svchb** [comment]
`https://github.com/user-attachments/assets/383d323a-3020-4232-9dc3-682b0afe8653`
![first_open_paraview_w_arrow](https://github.com/user-attachments/assets/383d323a-3020-4232-9dc3-682b0afe8653)

**Comment by efaulhaber** [comment]
```
https://github.com/user-attachments/assets/caf906e4-9e07-422e-8cf4-129add92e8c3
```
<img width="698" alt="grafik" src="https://github.com/user-attachments/assets/caf906e4-9e07-422e-8cf4-129add92e8c3">

**Comment by efaulhaber** [comment]
```
https://github.com/user-attachments/assets/862a1189-b758-4bad-b1e2-6abc42870bb2
```
<img width="1130" alt="grafik" src="https://github.com/user-attachments/assets/862a1189-b758-4bad-b1e2-6abc42870bb2">

**Comment by efaulhaber** [comment]
![n_body_serial](https://github.com/user-attachments/assets/ad45fdb7-a443-45eb-885e-263640626047)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/2b79188c-3148-49f1-8337-718721851bf5
```

![Image](https://github.com/user-attachments/assets/2b79188c-3148-49f1-8337-718721851bf5)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/f7376b15-324a-4da1-bb59-db01c7bd6620
```
![Image](https://github.com/user-attachments/assets/f7376b15-324a-4da1-bb59-db01c7bd6620)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/0f7aba29-3cf7-4ec1-8c95-841e72fe620d
```
![Image](https://github.com/user-attachments/assets/0f7aba29-3cf7-4ec1-8c95-841e72fe620d)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/7fe9d1f1-1633-4377-8b97-a4d1778aee07
```
![Image](https://github.com/user-attachments/assets/7fe9d1f1-1633-4377-8b97-a4d1778aee07)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/1501718f-d1f5-4f14-b1bc-2a2e581db476
```
![Image](https://github.com/user-attachments/assets/1501718f-d1f5-4f14-b1bc-2a2e581db476)

**Comment by LasNikas** [comment]
```
https://github.com/user-attachments/assets/4be889d6-e70a-4c5e-bef2-0071ea4d898c
```
![Image](https://github.com/user-attachments/assets/4be889d6-e70a-4c5e-bef2-0071ea4d898c)

**Comment by efaulhaber** [comment]
```
https://github.com/user-attachments/assets/ccf4e567-0adb-490e-9c2c-f36217dd5ca3
```
<img width="1917" height="1077" alt="Image" src="https://github.com/user-attachments/assets/ccf4e567-0adb-490e-9c2c-f36217dd5ca3" />

```
https://github.com/user-attachments/assets/a9fd65de-13dc-424d-b518-e7f4b417eff3
```
<img width="1920" height="1077" alt="Image" src="https://github.com/user-attachments/assets/a9fd65de-13dc-424d-b518-e7f4b417eff3" />
