### ISSUE TITLE
Add DOI badge, bibtex citation info to `README.md`; create `CITATION.bib` file

### ISSUE THREAD

**Issue by sloede** [trixi-framework/TrixiParticles.jl#450]
The generic DOI pointing to the latest release is [`10.5281/zenodo.10797541`](https://doi.org/10.5281/zenodo.10797541).

For citation info, see, e.g., https://github.com/trixi-framework/Trixi.jl#referencing.

For the `CITATION.bib` file, see, e.g., https://github.com/sloede/SecureArithmetic.jl/blob/main/CITATION.bib.

**Comment by svchb** [comment]
Fixed by #469.

**Comment by efaulhaber** [comment]
Ah, didn't even see this issue. Oops.
