### ISSUE TITLE
Different errors with and without threading

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/TrixiParticles.jl#481]
See #453.

**Comment by efaulhaber** [comment]
Update: I also get different errors on an x86 machine now...

**Comment by svchb** [comment]
> Update: I also get different errors on an x86 machine now...

This has been cleared up. This is caused by the optimization in #475 when using the inverted loop.

**Comment by efaulhaber** [comment]
Update: I get a validation error of `0.0` between single and multithreaded simulations on both an x86 Threadripper 3990X and an ARM Apple M2 Pro with #581.

So I guess the bug Heisenbug somehow disappeared? Closing this for now and hoping that it won't come back...
