### ISSUE TITLE
[Docs] Getting started page claims a plot is automatically diplayed, but it isn't

### ISSUE THREAD

**Issue by giordano** [trixi-framework/TrixiParticles.jl#629]
The example at https://trixi-framework.github.io/TrixiParticles.jl/v0.2.2/getting_started/#Running-an-Example claims that a plot is automatically displayed, but that's not the case, and I don't see how that'd happen, since there's nothing about plotting in the code at https://github.com/trixi-framework/TrixiParticles.jl/blob/b51cd2664b02d4dc98600dd8aeadf61a6c66e125/examples/fluid/hydrostatic_water_column_2d.jl.

Reproducer:
```julia
using Pkg
Pkg.add(["TrixiParticles", "OrdinaryDiffEq", "Plots"])
using TrixiParticles
trixi_include(joinpath(examples_dir(), "fluid", "hydrostatic_water_column_2d.jl"))
```

**Comment by efaulhaber** [comment]
Thanks for catching this! The `plot(sol)` got lost somewhere.

**Comment by LasNikas** [comment]
Thanks again for catching this. We'll fix it ASAP.
The bug is in the order of the parametes: https://github.com/trixi-framework/TrixiParticles.jl/blob/b51cd2664b02d4dc98600dd8aeadf61a6c66e125/src/visualization/recipes_plots.jl#L2
